# Starter pipeline
- task: Checkmarx AST@3
  inputs:
    CheckmarxService: 'AST Instance'
    projectName: '$(Build.Repository.Name)'
    branchName: '$(Build.SourceBranchName)'
    tenantName: 'mt_demo_ast'
- task: Checkmarx AST@3
  inputs:
    projectName: '$(Build.Repository.Name)'
    branchName: '$(Build.SourceBranchName)'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
